### ISSUE TITLE
使用体验及部分需求

### ISSUE THREAD

**Issue by imtck** [GMYXDS/MstscManager#1]
首先软件信息获取来源在热榜，看到远程管理，于是下载体验了下，很惊喜

![image](https://user-images.githubusercontent.com/48142859/197151532-d80f3dba-2399-414a-8cdc-ddfcd1869823.png)

软件优点显而易见的，巧妙集成了多种远控终端，虽然是调用第三方程序，但是也使得管理更加的方便
多种配置兼容，可见用了心的。（导入导出TXT部分能感觉明显卡顿，是否可以进一步优化）

## 不过在使用中还是有一些小需求：
+ 分类这块是否可以考虑多级？有些时候不一定用到，但是用到没有就会有点痛苦
+ RealVNC走自定义配置的时候，能否导出时候也支持导出配置路径，这样迁移或者数据丢失重置之后不用重新自定义配置了
+ 如果增加总数量显示或者增加id列？是不是会有一些帮助？
![image](https://user-images.githubusercontent.com/48142859/197155808-6da640c7-ec9e-4852-8f57-7192baa29ff3.png)

最后：下面这个是否是属于bug呢？
![image](https://user-images.githubusercontent.com/48142859/197157182-12f43636-5d4a-4bd4-a7ad-4c74de0757d2.png)

**Comment by GMYXDS** [comment]
1.关于导入导出卡顿已修复
2.V1.2已支持二级分类
3.导出配置已支持导出自定义字符串
4.已增加当前分类信息统计
5.最后404bug已修复
@imtck 
V1.2已发布，欢迎下载体验
