### ISSUE TITLE
v1.3 BUG

### ISSUE THREAD

**Issue by sifanx** [GMYXDS/MstscManager#4]
编辑主机 - 密码 右边的查看按钮，按要求输入管理员密码以后，并没有显示出明文密码，而是提示到账号管理里去查看，进入账号管理里又什么都没看到，是空的，但是在主机列表的详细信息里，点查看密码，输入管理员密码后，能正常看到明文的密码。

**Comment by sifanx** [comment]
额外信息 里的 转发组合键，也是反的，选择“在远程计算机上”，组合键无法在远程机里实现，改成“在这台计算机上”，就可以在远程机里使用组合键了，麻烦修改一下哦。

**Comment by GMYXDS** [comment]
V1.4修复
