### ISSUE TITLE
WIN10 导入数据之后一直闪退

### ISSUE THREAD

**Issue by ghost** [GMYXDS/MstscManager#5]
WIN10 导入数据之后一直闪退

**Comment by GMYXDS** [comment]
录屏截图看看

**Comment by ghost** [comment]
闪退问题找到了 ,导出数据的时候带逗号的密码会被拆分 然后导致导入失败闪退,但是现在问题是把拆分的带逗号的密码还原之后再导入, 带有逗号的密码的那一行配置无法导入.

**Comment by GMYXDS** [comment]
如果有内容包含逗号的，用单引号包裹起来  =>  ‘pass，word’
